### ISSUE TITLE
Complete in interactive (inferior-fsharp buffer)

### ISSUE THREAD

**Issue by fractus** [fsharp/emacs-fsharp-mode#200] opened 2019-04-07 20:22 UTC
### Description
There is no completion in the interactive console

### Repro steps
- Open any project
- `C-s` to start the interactive with
```
dotnet fsi --readline+
```

### Expected behavior
Some symbol completion similar to `.fs` or `fsx` buffers?

### Actual behavior
Complete after `List.` with `C-c C-.` has no effect.

### Known workarounds
None

### Related information 
Same behaviour with `readline-`

* Operating system: Win10 and Win10 WSL Ubuntu 16.04
* Branch: Package version 20190304.1317
* Emacs version: 26.1 (Win10), 25.3.2 (Win10 WSL)
* .NET Runtime, CoreCLR or Mono Version: .NET Core 2.2.202
* Performance information, links to performance testing scripts

**Comment by juergenhoetzel** [comment] 2019-04-07 21:06
Duplicate of #184

@jdodds  started to work on:
https://github.com/fsharp/emacs-fsharp-mode/pull/197

Any help is appreciated

**Closed by juergenhoetzel** 2019-04-07 21:06 UTC
Labels: duplicate
